---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_inventory: ./hosts
  ansible_sudo: true
#  ansible_verbose: true
#  ansible_verbosity: 2
  playbook: mysql.yml
  roles_path: ./roles/

verifier: 
  name: inspec

platforms:
  - name: centos
    driver_plugin: vagrant
    driver_config:
      box: bento/centos-7.4
      network:
      - ['forwarded_port', {guest: 3306, host: 3306}]
      - ['private_network', {ip: '192.168.68.10'}]

suites:
  - name: mysql
    verifier:
      inspec_tests:
        - test
        - https://github.com/artem-shorokhov/inspec-workshop.git

# Workaround to avoid 'SCP upload failed (open failed (1))'.
transport:
  max_ssh_sessions: 6
  